#!/usr/bin/env python3
"""the-card — full schematic in SKiDL, emits a KiCad netlist.

The electrical design of the ESP32-S3 e-paper smart badge, expressed in code.
Running this file instantiates every part, wires every net, runs ERC, and writes
hardware/the-card.net (importable into KiCad PCBNEW for layout).

    cd hardware && uv run python circuit.py

Parts come from two project libraries (regenerated by scripts/fetch_libs.sh):
  - 'the-card'  : actives/ICs/connectors fetched from LCSC
  - 'passives'  : generic R/C and the e-ink FPC connector templates

The electrical pinouts and reference circuits are datasheet-verified. PCB work
must still validate the NFC antenna geometry and the selected battery cable
polarity before fabrication.
"""
import os
import tempfile
from pathlib import Path

# Keep SKiDL's generated library cache out of the source tree and user profile.
os.environ.setdefault(
    "XDG_DATA_HOME",
    os.path.join(tempfile.gettempdir(), "the-card-xdg"),
)
os.environ.setdefault(
    "MPLCONFIGDIR",
    os.path.join(tempfile.gettempdir(), "the-card-matplotlib"),
)

DEFAULT_KICAD_SYMBOL_DIR = Path(
    "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols"
)
if DEFAULT_KICAD_SYMBOL_DIR.is_dir():
    for version in range(6, 11):
        os.environ.setdefault(
            f"KICAD{version}_SYMBOL_DIR",
            str(DEFAULT_KICAD_SYMBOL_DIR),
        )
    os.environ.setdefault("KICAD_SYMBOL_DIR", str(DEFAULT_KICAD_SYMBOL_DIR))

from skidl import lib_search_paths, Part, Net, ERC, generate_netlist

HERE = os.path.dirname(os.path.abspath(__file__))
for k in ("kicad8", "kicad10"):
    lib_search_paths[k].insert(0, os.path.join(HERE, "libraries"))

KICAD_SYMBOL_DIR = Path(
    os.environ.get("KICAD10_SYMBOL_DIR", DEFAULT_KICAD_SYMBOL_DIR)
)
if KICAD_SYMBOL_DIR.is_dir():
    lib_search_paths["kicad10"].insert(0, str(KICAD_SYMBOL_DIR))

ACT = "the-card"    # actives library
GEN = "passives"    # passives / connector templates

# ─────────────────────────────────────────────────────────────────────────────
# Part → symbol map (authoritative; mirrors parts.yaml)
# ─────────────────────────────────────────────────────────────────────────────
SYM = {
    "U1_MCU":   (ACT, "ESP32-S3-WROOM-1"),
    "U2_NFC":   (ACT, "ST25DV04KC-IE8S3"),
    "U3_IMU":   (ACT, "LSM6DSOTR"),
    "U4_SHT":   (ACT, "SHT40-BD1B-R2"),
    "U5_FG":    (ACT, "MAX17048G+T10"),
    "U6_CHG":   (ACT, "TP4056_C382139"),
    "U7_PROT":  (ACT, "DW01A_C18164398"),
    "U8_FET":   (ACT, "FS8205A"),
    "U9_LDO":   (ACT, "ME6211C33M5G-N"),
    "U10_ESD":  (ACT, "USBLC6-2SC6"),
    "Q1":       (ACT, "SI2301CDS-T1-GE3"),
    "Q2":       (ACT, "SI2301CDS-T1-GE3"),
    "D1_LED":   (ACT, "WS2812B-MINI"),
    "J1_USBC":  (ACT, "TYPE-C-31-M-12"),
    "SW_UP":    (ACT, "TS-1187A-B-A-B"),
    "SW_DN":    (ACT, "TS-1187A-B-A-B"),
    "SW_SEL":   (ACT, "TS-1187A-B-A-B"),
    "SW_MENU":  (ACT, "TS-1187A-B-A-B"),
    "J2_EPD":   (ACT, "FPC0.5-24PLTH2.0"),
}
R_FP = "Resistor_SMD:R_0402_1005Metric"
C0402 = (GEN, "CL05B104KO5NNNC", "Capacitor_SMD:C_0402_1005Metric")
C0603 = (GEN, "CL10A106KP8NNNC", "Capacitor_SMD:C_0603_1608Metric")
C_FP = {
    "0402": "Capacitor_SMD:C_0402_1005Metric",
    "0603": "Capacitor_SMD:C_0603_1608Metric",
    "0805": "Capacitor_SMD:C_0805_2012Metric",
}

# Conventional reference designators (override each symbol's default prefix)
REF = {
    "U1_MCU": "U1", "U2_NFC": "U2", "U3_IMU": "U3", "U4_SHT": "U4",
    "U5_FG": "U5", "U6_CHG": "U6", "U7_PROT": "U7", "U8_FET": "U8",
    "U9_LDO": "U9", "U10_ESD": "U10",
    "Q1": "Q1", "Q2": "Q2", "D1_LED": "D1",
    "J1_USBC": "J1", "J2_EPD": "J2",
    "SW_UP": "SW1", "SW_DN": "SW2", "SW_SEL": "SW3", "SW_MENU": "SW4",
}

# Keep semantic names in the Python design while emitting conventional KiCad
# reference designators for annotation, PCB synchronization, and BOM export.
SEMANTIC_REFS = {
    "R_en": "R1",
    "R_io0": "R2",
    "R_vbh": "R3",
    "R_vbl": "R4",
    "R_cc1": "R5",
    "R_cc2": "R6",
    "R_prog": "R7",
    "R_chrg": "R8",
    "R_dvcc": "R9",
    "R_dvm": "R10",
    "R_q1g": "R11",
    "R_q2g": "R12",
    "R_scl": "R13",
    "R_sda": "R14",
    "R_epdg": "R15",
    "R_epds": "R16",
    "C_mcu1": "C1",
    "C_mcu2": "C2",
    "C_en": "C3",
    "C_vb": "C4",
    "C_vbus": "C5",
    "C_bat": "C6",
    "C_dprot": "C7",
    "C_ldoi": "C8",
    "C_ldoo": "C9",
    "C_fg": "C10",
    "C_nfc": "C11",
    "C_imu1": "C12",
    "C_imu2": "C13",
    "C_sht": "C14",
    "C_led": "C15",
    "C_btn1": "C16",
    "C_btn2": "C17",
    "C_btn3": "C18",
    "C_btn4": "C19",
    "C_epd_in": "C20",
    "C_epd_pump": "C21",
    "C_epdvdd": "C22",
    "C_epd_vsh2": "C23",
    "C_epd_vsh1": "C24",
    "C_epd_vgh": "C25",
    "C_epd_vsl": "C26",
    "C_epd_vgl": "C27",
    "C_epd_vcom": "C28",
}


def physical_ref(semantic_ref):
    """Translate a semantic passive name to its conventional designator."""
    if semantic_ref.startswith(("R_", "C_")):
        return SEMANTIC_REFS[semantic_ref]
    return SEMANTIC_REFS.get(semantic_ref, semantic_ref)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers (always connect via NET += pin, which handles multi-pin pinlists)
# ─────────────────────────────────────────────────────────────────────────────
def part(key, value=None, footprint=None):
    lib, name = SYM[key]
    p = Part(lib, name, footprint=footprint)
    p.ref = REF[key]
    if value is not None:
        p.value = value
    return p


def R(value, ref):
    r = Part(GEN, "0402WGF1002TCE", footprint=R_FP)
    r.ref, r.value = physical_ref(ref), value
    return r


def C(value, ref, size="0402"):
    lib, name, _ = C0402 if size == "0402" else C0603
    c = Part(lib, name, footprint=C_FP[size])
    c.ref, c.value = physical_ref(ref), value
    return c


def std_part(library, name, value, ref, footprint):
    """Create a part from KiCad's standard symbol libraries."""
    component = Part(library, name, footprint=footprint)
    component.ref, component.value = ref, value
    return component


def decouple(net, ref, size="0402"):
    """100nF (or 10µF for 0603) from `net` to gnd."""
    c = C("100nF" if size == "0402" else "10uF", ref, size)
    net += c[1]
    c[2] += gnd
    return c


# ─────────────────────────────────────────────────────────────────────────────
# Power nets
# ─────────────────────────────────────────────────────────────────────────────
gnd     = Net("GND")
vbus    = Net("VBUS")        # +5V from USB-C
bat     = Net("+BAT")        # cell+ (raw battery); = TP4056.BAT, DW01.VDD, LDO.VIN, FG.CELL
p3v3    = Net("+3V3")        # system rail (always on, from LDO)
aux     = Net("AUX_3V3")     # switchable status-LED rail, gated by Q1
epd_p   = Net("EPD_VCI")     # e-ink VCI/VDDIO + booster input, gated by Q2
bat_neg = Net("BAT_NEG")     # cell- (before protection FETs)  ⚠️ NOT system GND


# ─────────────────────────────────────────────────────────────────────────────
# Battery connector — cell side of the on-board DW01A/FS8205A protection stage.
# Pin 1 is cell positive; pin 2 is cell negative. Verify cable polarity because
# JST-PH battery leads are not universally wired the same way.
# ─────────────────────────────────────────────────────────────────────────────
battery = std_part(
    "Connector_Generic",
    "Conn_01x02",
    "BATTERY 1S JST-PH",
    "J3",
    "Connector_JST:JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal",
)
bat += battery["1"]
bat_neg += battery["2"]

# ─────────────────────────────────────────────────────────────────────────────
# U1 — ESP32-S3-WROOM-1 (MCU)
# ─────────────────────────────────────────────────────────────────────────────
mcu = part("U1_MCU", value="ESP32-S3-WROOM-1-N8R2")
p3v3 += mcu["3V3"]
gnd   += mcu["GND"]
decouple(p3v3, "C_mcu1"); decouple(p3v3, "C_mcu2", "0603")  # 100nF + 10µF on 3V3

# EN: pullup to 3V3 (no reset button) + 1µF to GND
mcu_en = Net("MCU_EN")
mcu_en += mcu["EN"]
r_en = R("10k", "R_en"); p3v3 += r_en[1]; r_en[2] += mcu_en
c_en = C("1uF", "C_en", "0603"); mcu_en += c_en[1]; c_en[2] += gnd

# IO0: pullup to 3V3 (boot strap)
mcu_boot = Net("MCU_BOOT")
mcu_boot += mcu["IO0"]
r_io0 = R("10k", "R_io0"); p3v3 += r_io0[1]; r_io0[2] += mcu_boot

# USB (native, via ESD below)
usb_dm, usb_dp = Net("USB_DM"), Net("USB_DP")
usb_dm += mcu["IO19"]   # USB_D-
usb_dp += mcu["IO20"]   # USB_D+

# E-ink SPI
n_epd_mosi = Net("EPD_SDA"); n_epd_sclk = Net("EPD_SCLK")
n_epd_cs = Net("EPD_CS");    n_epd_dc = Net("EPD_DC")
n_epd_rst = Net("EPD_RST");  n_epd_busy = Net("EPD_BUSY")
n_epd_mosi += mcu["IO9"];  n_epd_sclk += mcu["IO10"]
n_epd_cs += mcu["IO12"];   n_epd_dc += mcu["IO13"]
n_epd_rst += mcu["IO14"];  n_epd_busy += mcu["IO11"]

# I2C bus (shared by NFC, IMU, SHT40, fuel gauge) + pullups
i2c_scl, i2c_sda = Net("I2C_SCL"), Net("I2C_SDA")
i2c_scl += mcu["IO8"]; i2c_sda += mcu["IO18"]
r_scl = R("4.7k", "R_scl"); p3v3 += r_scl[1]; r_scl[2] += i2c_scl
r_sda = R("4.7k", "R_sda"); p3v3 += r_sda[1]; r_sda[2] += i2c_sda

# Interrupts / status
nfc_irq, imu_int, chrg_stat = Net("NFC_IRQ"), Net("IMU_INT"), Net("~CHRG")
nfc_irq += mcu["IO3"]; imu_int += mcu["IO2"]; chrg_stat += mcu["IO15"]

# Buttons (to GND, internal RTC pullups; 100nF HW debounce)
btn_up = Net("BTN_UP"); btn_dn = Net("BTN_DOWN")
btn_sel = Net("BTN_SEL"); btn_menu = Net("BTN_MENU")
btn_up += mcu["IO4"]; btn_dn += mcu["IO5"]
btn_sel += mcu["IO6"]; btn_menu += mcu["IO7"]
for net, ref in [(btn_up, "C_btn1"), (btn_dn, "C_btn2"),
                 (btn_sel, "C_btn3"), (btn_menu, "C_btn4")]:
    c = C("100nF", ref); net += c[1]; c[2] += gnd

# Power-rail gate controls
# (GPIO33/34 are NOT broken out on WROOM-1 — reserved by internal SPI.)
pwr_aux = Net("PWR_AUX"); epd_pwr = Net("EPD_PWR_EN")
pwr_aux += mcu["IO47"]; epd_pwr += mcu["IO16"]

# WS2812 data. GPIO21 is intentionally left free for future expansion.
led_din = Net("LED_DIN")
led_din += mcu["IO48"]

# Battery voltage divider (backup; MAX17048 is primary). IO1 = ADC1_CH0.
dvr_hi = R("1M", "R_vbh"); dvr_lo = R("300k", "R_vbl")
bat += dvr_hi[1]; dvr_hi[2] += dvr_lo[1]; dvr_lo[2] += gnd
vbatt_sense = dvr_hi[2]; vbatt_sense += mcu["IO1"]
c_vb = C("100nF", "C_vb"); vbatt_sense += c_vb[1]; c_vb[2] += gnd


# ─────────────────────────────────────────────────────────────────────────────
# USB-C input + ESD (J1, U10)
# ─────────────────────────────────────────────────────────────────────────────
usbc = part("J1_USBC")
esd = part("U10_ESD")
vbus += usbc["VBUS"]
gnd += usbc["GND"]
gnd += usbc["EH"]                       # shell / mount tabs
# CC1/CC2 -> 5.1k to GND (UFP / power sink)
for cc, ref in [("CC1", "R_cc1"), ("CC2", "R_cc2")]:
    r = R("5.1k", ref); r[1] += usbc[cc]; r[2] += gnd
# D+/D- through USBLC6-2SC6 (1,6=I/O1=D-; 3,4=I/O2=D+; 2=GND; 5=VBUS)
esd["1"] += usbc["DN1"]; esd["1"] += usbc["DN2"]   # D- in (both orientations)
esd["3"] += usbc["DP1"]; esd["3"] += usbc["DP2"]   # D+ in
usb_dm += esd["6"]                                  # D- out to MCU
usb_dp += esd["4"]                                  # D+ out to MCU
gnd += esd["2"]; vbus += esd["5"]
decouple(vbus, "C_vbus", "0603")


# ─────────────────────────────────────────────────────────────────────────────
# Battery charger TP4056 (U6)
# ─────────────────────────────────────────────────────────────────────────────
chg = part("U6_CHG")
vbus += chg["VCC"]; bat += chg["BAT"]; gnd += chg["GND"]; gnd += chg["EP"]
rp = R("2.2k", "R_prog"); rp[1] += chg["PROG"]; rp[2] += gnd   # ~500mA from RPROG=1100V/IBAT
gnd += chg["TEMP"]                  # no NTC
vbus += chg["CE"]                   # always enabled while powered
rc = R("10k", "R_chrg"); p3v3 += rc[1]; rc[2] += chg["~{CHRG}"]
chrg_stat += chg["~{CHRG}"]         # open-drain status -> MCU
decouple(bat, "C_bat", "0603")


# ─────────────────────────────────────────────────────────────────────────────
# Battery protection DW01A (U7) + FS8205A (U8)   ✓ VERIFIED vs datasheets
# DW01A pins (EasyEDA = HMSEMI naming): 1=DOUT(DO, discharge gate), 2=VM(CS, sense),
# 3=COUT(CO, charge gate), 4=NC, 5=VDD(VCC, +supply via R1), 6=VSS(B-).
# Protection on the NEGATIVE path: +BAT is common; cell- (BAT_NEG) and P- (GND)
# are separated by the back-to-back FETs. The selected DW01A recommends
# R1=100Ω (VCC<-B+), R2=1kΩ (VM<-P-), and C1=100nF (VCC-VSS).
# FS8205A G1 controls the cell-negative/discharge FET; G2 controls the
# pack-negative/charge FET.
# ─────────────────────────────────────────────────────────────────────────────
prot = part("U7_PROT")
fet = part("U8_FET")
r_dvcc = R("100", "R_dvcc"); bat += r_dvcc[1]; r_dvcc[2] += prot["VDD"]          # R1
r_dvm  = R("1k",  "R_dvm");  gnd += r_dvm[1]; r_dvm[2] += prot["VM"]             # R2 (P- sense)
bat_neg += prot["VSS"]                                                       # B-
c_dprot = C("100nF", "C_dprot"); prot["VDD"] += c_dprot[1]; c_dprot[2] += bat_neg  # C1
prot["DOUT"] += fet["G1"]   # discharge gate -> cell-negative FET (S1=B-)
prot["COUT"] += fet["G2"]   # charge gate -> pack-negative FET (S2=P-)
bat_neg += fet["S1"]; gnd += fet["S2"]
fet_drain = Net("FET_DRAIN"); fet_drain += fet["D12"]   # internal common-drain node


# ─────────────────────────────────────────────────────────────────────────────
# LDO 3.3V ME6211 (U9) — always-on system rail
# ─────────────────────────────────────────────────────────────────────────────
ldo = part("U9_LDO")
bat += ldo["VIN"]; p3v3 += ldo["VOUT"]; gnd += ldo["VSS"]; bat += ldo["CE"]
c_ldoi = C("1uF", "C_ldoi", "0603"); bat += c_ldoi[1]; c_ldoi[2] += gnd
c_ldoo = C("1uF", "C_ldoo", "0603"); p3v3 += c_ldoo[1]; c_ldoo[2] += gnd


# ─────────────────────────────────────────────────────────────────────────────
# Fuel gauge MAX17048 (U5) — always on, monitors +BAT
# ─────────────────────────────────────────────────────────────────────────────
fg = part("U5_FG")
bat += fg["CELL"]; bat += fg["VDD"]; gnd += fg["GND"]; gnd += fg["EP"]
i2c_scl += fg["SCL"]; i2c_sda += fg["SDA"]
gnd += fg["CTG"]; gnd += fg["QSTRT"]
# ~ALRT left NC (could route to a spare GPIO)
decouple(bat, "C_fg")


# ─────────────────────────────────────────────────────────────────────────────
# Switchable AUX branch rail (Q1) — sensors + LED cut during deep sleep
# P-MOSFET high-side: S=+3V3, D=AUX_3V3, gate pulled high (off) + driven by PWR_AUX
# ─────────────────────────────────────────────────────────────────────────────
q1 = part("Q1")
p3v3 += q1["S"]; aux += q1["D"]; pwr_aux += q1["G"]
r_q1g = R("10k", "R_q1g"); p3v3 += r_q1g[1]; r_q1g[2] += pwr_aux    # gate pullup (off)

# Q2 gates e-ink panel VDD for zero-idle current
q2 = part("Q2")
p3v3 += q2["S"]; epd_p += q2["D"]; epd_pwr += q2["G"]
r_q2g = R("10k", "R_q2g"); p3v3 += r_q2g[1]; r_q2g[2] += epd_pwr


# ─────────────────────────────────────────────────────────────────────────────
# NFC ST25DV04KC (U2)   ✓ VERIFIED vs ST datasheet (internal tuning C = 28.5 pF;
#   antenna goes straight on AC0/AC1 — no external tuning cap. Both pins share
#   one PCB net so the board editor can route a continuous ~4.8uH loop.)
# ─────────────────────────────────────────────────────────────────────────────
nfc = part("U2_NFC")
p3v3 += nfc["VCC"]; gnd += nfc["VSS"]
i2c_scl += nfc["SCL"]; i2c_sda += nfc["SDA"]
nfc_irq += nfc["GPO"]            # RF-field / msg interrupt -> MCU
# V_EH is intentionally unconnected in this core revision.
nfc_antenna = Net("NFC_ANTENNA")
nfc_antenna += nfc["AC0"]
nfc_antenna += nfc["AC1"]
decouple(p3v3, "C_nfc")


# ─────────────────────────────────────────────────────────────────────────────
# IMU LSM6DSO (U3) — always-on rail; I2C mode. Keeping I2C devices powered
# avoids back-powering them through the always-on bus pull-ups.
# ─────────────────────────────────────────────────────────────────────────────
imu = part("U3_IMU")
p3v3 += imu["VDD"]; p3v3 += imu["VDDIO"]; gnd += imu["GND"]
i2c_scl += imu["SCL"]; i2c_sda += imu["SDA"]
imu_int += imu["INT1"]
p3v3 += imu["CS"]              # CS high -> I2C mode
gnd += imu["SDO/SA0"]          # I2C addr LSB = 0
decouple(p3v3, "C_imu1"); decouple(p3v3, "C_imu2", "0603")


# ─────────────────────────────────────────────────────────────────────────────
# Temp/Humidity SHT40 (U4) — always-on rail
# ─────────────────────────────────────────────────────────────────────────────
sht = part("U4_SHT")
p3v3 += sht["VDD"]; gnd += sht["VSS"]
i2c_scl += sht["SCL"]; i2c_sda += sht["SDA"]
decouple(p3v3, "C_sht")


# ─────────────────────────────────────────────────────────────────────────────
# RGB status LED WS2812B-Mini (D1) — on AUX rail (off in deep sleep)
# ─────────────────────────────────────────────────────────────────────────────
led = part("D1_LED")
aux += led["VDD"]; gnd += led["VSS"]; led_din += led["DIN"]
decouple(aux, "C_led")


# ─────────────────────────────────────────────────────────────────────────────
# Buttons SW1..SW4 (TS-1187A: pins A&C = switch terminals)
# ─────────────────────────────────────────────────────────────────────────────
for key, net in [("SW_UP", btn_up), ("SW_DN", btn_dn),
                 ("SW_SEL", btn_sel), ("SW_MENU", btn_menu)]:
    sw = part(key)
    net += sw["A"]; gnd += sw["C"]


# ─────────────────────────────────────────────────────────────────────────────
# E-ink panel connector J2 — GDEY029T94 24-pin FFC   ✓ VERIFIED vs Good Display
# reference circuit. The bare panel requires the complete host-side SSD1680
# booster, charge pump, and high-voltage bypass network below.
# Pin map (FPC 1-24 = signals, 25-26 = shell):
#   8=BS1 9=BUSY 10=RES# 11=D/C# 12=CS# 13=SCL 14=SDA 15=VDDIO 16=VCI 17=VSS 18=VDD
# ─────────────────────────────────────────────────────────────────────────────
epd = part(
  "J2_EPD",
  value="FH12-24S-0.5SH(55)",
  footprint=(
    "the-card:"
    "Hirose_FH12-24S-0.5SH_1x24-2MP_P0.50mm_Horizontal"
  ),
)
epd.datasheet = "https://www.hirose.com/product/p/CL0586-0521-0-55"
gnd += epd["8"]                                                       # BS1 = L -> 4-wire SPI
n_epd_busy += epd["9"]; n_epd_rst += epd["10"]                        # BUSY / RES#
n_epd_dc   += epd["11"]; n_epd_cs  += epd["12"]                        # D/C# / CS#
n_epd_sclk += epd["13"]; n_epd_mosi += epd["14"]                       # SCL / SDA(MOSI)
epd_p += epd["15"]; epd_p += epd["16"]                                # VDDIO + VCI
gnd   += epd["17"]                                                    # VSS
gnd += epd["25"]; gnd += epd["26"]                                    # shell / mount pads

# Panel-specific boost/charge-pump network (Good Display GDEY029T94 §12).
epd_gdr = Net("EPD_GDR"); epd_gdr += epd["2"]
epd_rese = Net("EPD_RESE"); epd_rese += epd["3"]
epd_vsh2 = Net("EPD_VSH2"); epd_vsh2 += epd["5"]
epd_vsh1 = Net("EPD_VSH1"); epd_vsh1 += epd["20"]
epd_vgh = Net("EPD_VGH"); epd_vgh += epd["21"]
epd_vsl = Net("EPD_VSL"); epd_vsl += epd["22"]
epd_vgl = Net("EPD_VGL"); epd_vgl += epd["23"]
epd_vcom = Net("EPD_VCOM"); epd_vcom += epd["24"]
epd_switch = Net("EPD_SW")
epd_pump = Net("EPD_PUMP")

l_epd = std_part(
    "Device", "L", "SRU5016-470Y 47uH", "L1",
    "Inductor_SMD:L_Bourns_SRU5016_5.2x5.2mm",
)
epd_p += l_epd["1"]
epd_switch += l_epd["2"]

q_epd = std_part(
    "Transistor_FET", "Q_NMOS_GSD", "Si1304BDL", "Q3",
    "Package_TO_SOT_SMD:SOT-323_SC-70",
)
epd_gdr += q_epd["G"]
epd_rese += q_epd["S"]
epd_switch += q_epd["D"]

r_epdg = R("1M", "R_epdg"); epd_gdr += r_epdg[1]; r_epdg[2] += gnd
r_epds = R("2.2", "R_epds"); epd_rese += r_epds[1]; r_epds[2] += gnd

d_epd_vgl = std_part(
    "Device", "D", "MBR0530", "D2", "Diode_SMD:D_SOD-123"
)
epd_pump += d_epd_vgl["K"]
epd_vgl += d_epd_vgl["A"]

d_epd_clamp = std_part(
    "Device", "D", "MBR0530", "D3", "Diode_SMD:D_SOD-123"
)
gnd += d_epd_clamp["K"]
epd_pump += d_epd_clamp["A"]

d_epd_vgh = std_part(
    "Device", "D", "MBR0530", "D4", "Diode_SMD:D_SOD-123"
)
epd_vgh += d_epd_vgh["K"]
epd_switch += d_epd_vgh["A"]

c_epd_in = C("4.7uF 25V", "C_epd_in", "0805")
epd_p += c_epd_in[1]; c_epd_in[2] += gnd
c_epd_pump = C("4.7uF 25V", "C_epd_pump", "0805")
epd_pump += c_epd_pump[1]; c_epd_pump[2] += epd_switch

epd_vdd_core = Net("EPD_VDD_CORE"); epd_vdd_core += epd["18"]
c_epdvdd = C("1uF 25V", "C_epdvdd", "0805")
epd_vdd_core += c_epdvdd[1]; c_epdvdd[2] += gnd
for net, ref in [
    (epd_vsh2, "C_epd_vsh2"),
    (epd_vsh1, "C_epd_vsh1"),
    (epd_vgh, "C_epd_vgh"),
    (epd_vsl, "C_epd_vsl"),
    (epd_vgl, "C_epd_vgl"),
    (epd_vcom, "C_epd_vcom"),
]:
    capacitor = C("1uF 25V", ref, "0805")
    net += capacitor[1]
    capacitor[2] += gnd


# ─────────────────────────────────────────────────────────────────────────────
# Bring-up test points. EN and IO0 can be momentarily shorted to GND for reset
# and ROM download recovery without adding two more user-facing buttons.
# ─────────────────────────────────────────────────────────────────────────────
for ref, value, net in [
    ("TP1", "+BAT", bat),
    ("TP2", "BAT_NEG", bat_neg),
    ("TP3", "+3V3", p3v3),
    ("TP4", "GND", gnd),
    ("TP5", "EN", mcu_en),
    ("TP6", "IO0", mcu_boot),
]:
    test_point = std_part(
        "Connector", "TestPoint", value, ref,
        "TestPoint:TestPoint_Pad_D1.0mm",
    )
    net += test_point["1"]


# ─────────────────────────────────────────────────────────────────────────────
# ERC + netlist
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    ERC()
    out = os.path.join(HERE, "the-card.net")
    generate_netlist(file_=out)
    print(f"OK netlist written: {out}")
