#!/usr/bin/env python3
"""the-card — full schematic in SKiDL, emits a KiCad netlist.

The electrical design of the ESP32-S3 e-paper smart badge, expressed in code.
Running this file instantiates every part, wires every net, runs ERC, and writes
hardware/the-card.net (importable into KiCad PCBNEW for layout).

    cd hardware && uv run python circuit.py

Parts come from two project libraries (regenerated by scripts/fetch_libs.sh):
  - 'the-card'  : actives/ICs/connectors fetched from LCSC
  - 'passives'  : generic R/C and the e-ink FPC connector templates

⚠️ Sections flagged "VERIFY" depend on datasheet details that must be confirmed
   before tape-out: DW01A+FS8205A protection topology, GDEY029T94 FPC pinout,
   and the ST25DV NFC antenna tuning.
"""
import os
from skidl import lib_search_paths, Part, Net, ERC, generate_netlist

HERE = os.path.dirname(os.path.abspath(__file__))
for k in ("kicad8", "kicad10"):
    lib_search_paths[k].insert(0, os.path.join(HERE, "libraries"))

ACT = "the-card"    # actives library
GEN = "passives"    # passives / connector templates

# ─────────────────────────────────────────────────────────────────────────────
# Part → symbol map (authoritative; mirrors parts.yaml)
# ─────────────────────────────────────────────────────────────────────────────
SYM = {
    "U1_MCU":   (ACT, "ESP32-S3-WROOM-1"),
    "U2_NFC":   (ACT, "ST25DV04KC-IE8S3"),
    "U3_IMU":   (ACT, "LSM6DSOTR"),
    "U4_SHT":   (ACT, "SHT40-BD1B-R2"),
    "U5_FG":    (ACT, "MAX17048G+T10"),
    "U6_CHG":   (ACT, "TP4056_C382139"),
    "U7_PROT":  (ACT, "DW01A_C18164398"),
    "U8_FET":   (ACT, "FS8205A"),
    "U9_LDO":   (ACT, "ME6211C33M5G-N"),
    "U10_ESD":  (ACT, "USBLC6-2SC6"),
    "Q1":       (ACT, "SI2301CDS-T1-GE3"),
    "Q2":       (ACT, "SI2301CDS-T1-GE3"),
    "D1_LED":   (ACT, "WS2812B-MINI"),
    "J1_USBC":  (ACT, "TYPE-C-31-M-12"),
    "SW_UP":    (ACT, "TS-1187A-B-A-B"),
    "SW_DN":    (ACT, "TS-1187A-B-A-B"),
    "SW_SEL":   (ACT, "TS-1187A-B-A-B"),
    "SW_MENU":  (ACT, "TS-1187A-B-A-B"),
    "J2_EPD":   (ACT, "FPC0.5-24PLTH2.0"),
}
R_FP = "Resistor_SMD:R_0402_1005Metric"
C0402 = (GEN, "CL05B104KO5NNNC", "Capacitor_SMD:C_0402_1005Metric")
C0603 = (GEN, "CL10A106KP8NNNC", "Capacitor_SMD:C_0603_1608Metric")

# Conventional reference designators (override each symbol's default prefix)
REF = {
    "U1_MCU": "U1", "U2_NFC": "U2", "U3_IMU": "U3", "U4_SHT": "U4",
    "U5_FG": "U5", "U6_CHG": "U6", "U7_PROT": "U7", "U8_FET": "U8",
    "U9_LDO": "U9", "U10_ESD": "U10",
    "Q1": "Q1", "Q2": "Q2", "D1_LED": "D1",
    "J1_USBC": "J1", "J2_EPD": "J2",
    "SW_UP": "SW1", "SW_DN": "SW2", "SW_SEL": "SW3", "SW_MENU": "SW4",
}


# ─────────────────────────────────────────────────────────────────────────────
# Helpers (always connect via NET += pin, which handles multi-pin pinlists)
# ─────────────────────────────────────────────────────────────────────────────
def part(key, value=None, footprint=None):
    lib, name = SYM[key]
    p = Part(lib, name, footprint=footprint)
    p.ref = REF[key]
    if value is not None:
        p.value = value
    return p


def R(value, ref):
    r = Part(GEN, "0402WGF1002TCE", footprint=R_FP)
    r.ref, r.value = ref, value
    return r


def C(value, ref, size="0402"):
    lib, name, fp = C0603 if size == "0603" else C0402
    c = Part(lib, name, footprint=fp)
    c.ref, c.value = ref, value
    return c


def decouple(net, ref, size="0402"):
    """100nF (or 10µF for 0603) from `net` to gnd."""
    c = C("100nF" if size == "0402" else "10uF", ref, size)
    net += c[1]
    c[2] += gnd
    return c


# ─────────────────────────────────────────────────────────────────────────────
# Power nets
# ─────────────────────────────────────────────────────────────────────────────
gnd     = Net("GND")
vbus    = Net("VBUS")        # +5V from USB-C
bat     = Net("+BAT")        # cell+ (raw battery); = TP4056.BAT, DW01.VDD, LDO.VIN, FG.CELL
p3v3    = Net("+3V3")        # system rail (always on, from LDO)
aux     = Net("AUX_3V3")     # switchable branch rail (sensors/LED), gated by Q1
epd_p   = Net("EPD_VDD")     # e-ink panel power, gated by Q2
bat_neg = Net("BAT_NEG")     # cell- (before protection FETs)  ⚠️ NOT system GND

# ─────────────────────────────────────────────────────────────────────────────
# U1 — ESP32-S3-WROOM-1 (MCU)
# ─────────────────────────────────────────────────────────────────────────────
mcu = part("U1_MCU", value="ESP32-S3-WROOM-1-N8R2")
p3v3 += mcu["3V3"]
gnd   += mcu["GND"]
decouple(p3v3, "C_mcu1"); decouple(p3v3, "C_mcu2", "0603")  # 100nF + 10µF on 3V3

# EN: pullup to 3V3 (no reset button) + 1µF to GND
r_en = R("10k", "R_en"); p3v3 += r_en[1]; r_en[2] += mcu["EN"]
c_en = C("1uF", "C_en", "0603"); mcu["EN"] += c_en[1]; c_en[2] += gnd

# IO0: pullup to 3V3 (boot strap)
r_io0 = R("10k", "R_io0"); p3v3 += r_io0[1]; r_io0[2] += mcu["IO0"]

# USB (native, via ESD below)
usb_dm, usb_dp = Net("USB_DM"), Net("USB_DP")
usb_dm += mcu["IO19"]   # USB_D-
usb_dp += mcu["IO20"]   # USB_D+

# E-ink SPI
n_epd_mosi = Net("EPD_SDA"); n_epd_sclk = Net("EPD_SCLK")
n_epd_cs = Net("EPD_CS");    n_epd_dc = Net("EPD_DC")
n_epd_rst = Net("EPD_RST");  n_epd_busy = Net("EPD_BUSY")
n_epd_mosi += mcu["IO9"];  n_epd_sclk += mcu["IO10"]
n_epd_cs += mcu["IO12"];   n_epd_dc += mcu["IO13"]
n_epd_rst += mcu["IO14"];  n_epd_busy += mcu["IO11"]

# I2C bus (shared by NFC, IMU, SHT40, fuel gauge) + pullups
i2c_scl, i2c_sda = Net("I2C_SCL"), Net("I2C_SDA")
i2c_scl += mcu["IO8"]; i2c_sda += mcu["IO18"]
r_scl = R("4.7k", "R_scl"); p3v3 += r_scl[1]; r_scl[2] += i2c_scl
r_sda = R("4.7k", "R_sda"); p3v3 += r_sda[1]; r_sda[2] += i2c_sda

# Interrupts / status
nfc_irq, imu_int, chrg_stat = Net("NFC_IRQ"), Net("IMU_INT"), Net("~CHRG")
nfc_irq += mcu["IO3"]; imu_int += mcu["IO2"]; chrg_stat += mcu["IO15"]

# Buttons (to GND, internal RTC pullups; 100nF HW debounce)
btn_up = Net("BTN_UP"); btn_dn = Net("BTN_DOWN")
btn_sel = Net("BTN_SEL"); btn_menu = Net("BTN_MENU")
btn_up += mcu["IO4"]; btn_dn += mcu["IO5"]
btn_sel += mcu["IO6"]; btn_menu += mcu["IO7"]
for net, ref in [(btn_up, "C_btn1"), (btn_dn, "C_btn2"),
                 (btn_sel, "C_btn3"), (btn_menu, "C_btn4")]:
    c = C("100nF", ref); net += c[1]; c[2] += gnd

# Power-rail gate controls
# (GPIO33/34 are NOT broken out on WROOM-1 — reserved by internal SPI.)
pwr_aux = Net("PWR_AUX"); epd_pwr = Net("EPD_PWR_EN")
pwr_aux += mcu["IO47"]; epd_pwr += mcu["IO16"]

# WS2812 + motor nets
led_din = Net("LED_DIN"); motor_pwm = Net("MOTOR_PWM")
led_din += mcu["IO48"]; motor_pwm += mcu["IO21"]

# Battery voltage divider (backup; MAX17048 is primary). IO1 = ADC1_CH0.
dvr_hi = R("1M", "R_vbh"); dvr_lo = R("300k", "R_vbl")
bat += dvr_hi[1]; dvr_hi[2] += dvr_lo[1]; dvr_lo[2] += gnd
vbatt_sense = dvr_hi[2]; vbatt_sense += mcu["IO1"]
c_vb = C("100nF", "C_vb"); vbatt_sense += c_vb[1]; c_vb[2] += gnd


# ─────────────────────────────────────────────────────────────────────────────
# USB-C input + ESD (J1, U10)
# ─────────────────────────────────────────────────────────────────────────────
usbc = part("J1_USBC")
esd = part("U10_ESD")
vbus += usbc["VBUS"]
gnd += usbc["GND"]
gnd += usbc["EH"]                       # shell / mount tabs
# CC1/CC2 -> 5.1k to GND (UFP / power sink)
for cc, ref in [("CC1", "R_cc1"), ("CC2", "R_cc2")]:
    r = R("5.1k", ref); r[1] += usbc[cc]; r[2] += gnd
# D+/D- through USBLC6-2SC6 (1,6=I/O1=D-; 3,4=I/O2=D+; 2=GND; 5=VBUS)
esd["1"] += usbc["DN1"]; esd["1"] += usbc["DN2"]   # D- in (both orientations)
esd["3"] += usbc["DP1"]; esd["3"] += usbc["DP2"]   # D+ in
usb_dm += esd["6"]                                  # D- out to MCU
usb_dp += esd["4"]                                  # D+ out to MCU
gnd += esd["2"]; vbus += esd["5"]
decouple(vbus, "C_vbus", "0603")


# ─────────────────────────────────────────────────────────────────────────────
# Battery charger TP4056 (U6)
# ─────────────────────────────────────────────────────────────────────────────
chg = part("U6_CHG")
vbus += chg["VCC"]; bat += chg["BAT"]; gnd += chg["GND"]; gnd += chg["EP"]
rp = R("1.2k", "R_prog"); rp[1] += chg["PROG"]; rp[2] += gnd   # I_chg = 1A
gnd += chg["TEMP"]                  # no NTC
vbus += chg["CE"]                   # always enabled while powered
rc = R("10k", "R_chrg"); p3v3 += rc[1]; rc[2] += chg["~{CHRG}"]
chrg_stat += chg["~{CHRG}"]         # open-drain status -> MCU
decouple(bat, "C_bat", "0603")


# ─────────────────────────────────────────────────────────────────────────────
# Battery protection DW01A (U7) + FS8205A (U8)   ⚠️ VERIFY vs reference design
# Protection on the NEGATIVE path: +BAT is common; cell- and P- (system GND)
# are separated by the back-to-back FETs.
# ─────────────────────────────────────────────────────────────────────────────
prot = part("U7_PROT")
fet = part("U8_FET")
bat += prot["VDD"]; bat_neg += prot["VSS"]; gnd += prot["VM"]
prot["COUT"] += fet["G1"]; prot["DOUT"] += fet["G2"]
bat_neg += fet["S1"]; gnd += fet["S2"]
fet_drain = Net("FET_DRAIN"); fet_drain += fet["D12"]   # internal common-drain node


# ─────────────────────────────────────────────────────────────────────────────
# LDO 3.3V ME6211 (U9) — always-on system rail
# ─────────────────────────────────────────────────────────────────────────────
ldo = part("U9_LDO")
bat += ldo["VIN"]; p3v3 += ldo["VOUT"]; gnd += ldo["VSS"]; bat += ldo["CE"]
c_ldoi = C("1uF", "C_ldoi", "0603"); bat += c_ldoi[1]; c_ldoi[2] += gnd
c_ldoo = C("1uF", "C_ldoo", "0603"); p3v3 += c_ldoo[1]; c_ldoo[2] += gnd


# ─────────────────────────────────────────────────────────────────────────────
# Fuel gauge MAX17048 (U5) — always on, monitors +BAT
# ─────────────────────────────────────────────────────────────────────────────
fg = part("U5_FG")
bat += fg["CELL"]; bat += fg["VDD"]; gnd += fg["GND"]; gnd += fg["EP"]
i2c_scl += fg["SCL"]; i2c_sda += fg["SDA"]
gnd += fg["CTG"]; gnd += fg["QSTRT"]
# ~ALRT left NC (could route to a spare GPIO)
decouple(bat, "C_fg")


# ─────────────────────────────────────────────────────────────────────────────
# Switchable AUX branch rail (Q1) — sensors + LED cut during deep sleep
# P-MOSFET high-side: S=+3V3, D=AUX_3V3, gate pulled high (off) + driven by PWR_AUX
# ─────────────────────────────────────────────────────────────────────────────
q1 = part("Q1")
p3v3 += q1["S"]; aux += q1["D"]; pwr_aux += q1["G"]
r_q1g = R("10k", "R_q1g"); p3v3 += r_q1g[1]; r_q1g[2] += pwr_aux    # gate pullup (off)

# Q2 gates e-ink panel VDD for zero-idle current
q2 = part("Q2")
p3v3 += q2["S"]; epd_p += q2["D"]; epd_pwr += q2["G"]
r_q2g = R("10k", "R_q2g"); p3v3 += r_q2g[1]; r_q2g[2] += epd_pwr


# ─────────────────────────────────────────────────────────────────────────────
# NFC ST25DV04KC (U2)   ⚠️ antenna geometry is a layout task
# ─────────────────────────────────────────────────────────────────────────────
nfc = part("U2_NFC")
p3v3 += nfc["VCC"]; gnd += nfc["VSS"]
i2c_scl += nfc["SCL"]; i2c_sda += nfc["SDA"]
nfc_irq += nfc["GPO"]            # RF-field / msg interrupt -> MCU
# V_EH (energy harvest) and AC0/AC1 (antenna) left as named nets for layout
nfc_eh = Net("NFC_EH"); nfc_eh += nfc["V_EH"]
nfc_ant_a = Net("NFC_ANT_A"); nfc_ant_a += nfc["AC0"]
nfc_ant_b = Net("NFC_ANT_B"); nfc_ant_b += nfc["AC1"]
decouple(p3v3, "C_nfc")


# ─────────────────────────────────────────────────────────────────────────────
# IMU LSM6DSO (U3) — on AUX rail; I2C mode
# ─────────────────────────────────────────────────────────────────────────────
imu = part("U3_IMU")
aux += imu["VDD"]; aux += imu["VDDIO"]; gnd += imu["GND"]
i2c_scl += imu["SCL"]; i2c_sda += imu["SDA"]
imu_int += imu["INT1"]
aux += imu["CS"]               # CS high -> I2C mode
gnd += imu["SDO/SA0"]          # I2C addr LSB = 0
decouple(aux, "C_imu1"); decouple(aux, "C_imu2", "0603")


# ─────────────────────────────────────────────────────────────────────────────
# Temp/Humidity SHT40 (U4) — on AUX rail
# ─────────────────────────────────────────────────────────────────────────────
sht = part("U4_SHT")
aux += sht["VDD"]; gnd += sht["VSS"]; gnd += sht["EP"]
i2c_scl += sht["SCL"]; i2c_sda += sht["SDA"]
decouple(aux, "C_sht")


# ─────────────────────────────────────────────────────────────────────────────
# RGB status LED WS2812B-Mini (D1) — on AUX rail (off in deep sleep)
# ─────────────────────────────────────────────────────────────────────────────
led = part("D1_LED")
aux += led["VDD"]; gnd += led["VSS"]; led_din += led["DIN"]
decouple(aux, "C_led")


# ─────────────────────────────────────────────────────────────────────────────
# Buttons SW1..SW4 (TS-1187A: pins A&C = switch terminals)
# ─────────────────────────────────────────────────────────────────────────────
for key, net in [("SW_UP", btn_up), ("SW_DN", btn_dn),
                 ("SW_SEL", btn_sel), ("SW_MENU", btn_menu)]:
    sw = part(key)
    net += sw["A"]; gnd += sw["C"]


# ─────────────────────────────────────────────────────────────────────────────
# E-ink panel connector J2 (24-pos FPC)   ⚠️ VERIFY pinout vs GDEY029T94 FPC
# Mapping per parts.yaml (1:GND,2:VDD,3:MOSI,4:SCLK,5:CS,6:DC,7:RST,8:BUSY).
# ─────────────────────────────────────────────────────────────────────────────
epd = part("J2_EPD")
gnd += epd["1"]
epd_p += epd["2"]
n_epd_mosi += epd["3"]; n_epd_sclk += epd["4"]
n_epd_cs += epd["5"]; n_epd_dc += epd["6"]
n_epd_rst += epd["7"]; n_epd_busy += epd["8"]
for p in range(9, 27):          # remaining signal + mount pads -> GND
    gnd += epd[str(p)]


# ─────────────────────────────────────────────────────────────────────────────
# ERC + netlist
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    ERC()
    out = os.path.join(HERE, "the-card.net")
    generate_netlist(file_=out)
    print(f"OK netlist written: {out}")
